[Build] Strengthen SVE compile check in FindARM.cmake
Add `vget_low_bf16` call, that exposes gcc-13.1 bug when mixing NEON and SVE
```
/usr/lib/gcc/aarch64-linux-gnu/13/include/arm_neon.h:28347:1: error: inlining failed in call to 'always_inline' 'bfloat16x4_t vget_low_bf16(bfloat16x8_t)': target specific option mismatch
```

Turn missing SVE support for Linux ARM compiler into fatal error, but overridable with `BUILD_IGNORE_SVE_UNAVAILABLE` envvar

ghstack-source-id: dc0622a51b2b25a11bb35ade64afa4621bd25d53
Pull-Request: https://github.com/pytorch/pytorch/pull/176646